services:
  apicurio-registry:
    image: apicurio/apicurio-registry:3.0.9
    ports:
      - "8080:8080"
    environment:
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:8888
      APICURIO_REST_DELETION_ARTIFACT_ENABLED: true
      APICURIO_REST_DELETION_GROUP_ENABLED: true

  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:3.0.9
    ports:
      - "8888:8080"
    environment:
      REGISTRY_API_URL: http://localhost:8080/apis/registry/v3
